#!/bin/sh
#
# An example hook script to prepare a packed repository for use over
# dumb transports.
#
# To enable this hook, rename this file to "post-update".

#exec git update-server-info

git checkout master
make html
git checkout bare
rsync -r --progress /var/www/html/productName-doc/* user@webhost.com:/var/www/html/productName-doc/
